server:
  port: 8081
  servlet-path: /api

spring:
  profiles:
    active: test

mybatis:
  type-aliases-package: com.syt.hotel.dao
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
