package com.syt.hotel.dao;

import java.util.List;

import com.syt.hotel.model.SytDept;
import com.syt.hotel.model.SytDeptExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

public interface SytDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    long countByExample(SytDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int deleteByExample(SytDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int insert(SytDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int insertSelective(SytDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    List<SytDept> selectByExample(SytDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    SytDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") SytDept record, @Param("example") SytDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByExample(@Param("record") SytDept record, @Param("example") SytDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByPrimaryKeySelective(SytDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_DEPT
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByPrimaryKey(SytDept record);
}