package com.syt.hotel.dao;

import java.util.List;

import com.syt.hotel.model.SytUserBook;
import com.syt.hotel.model.SytUserBookExample;
import org.apache.ibatis.annotations.Param;

public interface SytUserBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    long countByExample(SytUserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int deleteByExample(SytUserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int insert(SytUserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int insertSelective(SytUserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    List<SytUserBook> selectByExample(SytUserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    SytUserBook selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") SytUserBook record, @Param("example") SytUserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByExample(@Param("record") SytUserBook record, @Param("example") SytUserBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByPrimaryKeySelective(SytUserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER_BOOK
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByPrimaryKey(SytUserBook record);

    List<SytUserBook> findAllByPage(@Param("type") int type, @Param("userId") Long userId, @Param("start") int start, @Param("end") int end);

    int findAllByPageCount(@Param("type") int type, @Param("userId") Long userId);
}