package com.syt.hotel.dao;


import com.syt.hotel.model.SytUser;
import com.syt.hotel.model.SytUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SytUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    long countByExample(SytUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int deleteByExample(SytUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int insert(SytUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int insertSelective(SytUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    List<SytUser> selectByExample(SytUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    SytUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") SytUser record, @Param("example") SytUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByExample(@Param("record") SytUser record, @Param("example") SytUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByPrimaryKeySelective(SytUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYT_USER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    int updateByPrimaryKey(SytUser record);
}