package com.syt.hotel.model;

public class SytDept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_DEPT.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_DEPT.DEPT_NAME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_DEPT.ID
     *
     * @return the value of SYT_DEPT.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_DEPT.ID
     *
     * @param id the value for SYT_DEPT.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_DEPT.DEPT_NAME
     *
     * @return the value of SYT_DEPT.DEPT_NAME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_DEPT.DEPT_NAME
     *
     * @param deptName the value for SYT_DEPT.DEPT_NAME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
}