package com.syt.hotel.model;

import java.util.Date;

public class SytUserBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.USER_ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.BOOK_DATE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Date bookDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.BOOK_TYPE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Integer bookType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.FOOD_TYPE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Integer foodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.CHECK_UID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Long checkUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.CHECK_TIME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.CREATE_TIME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER_BOOK.STATUS
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.ID
     *
     * @return the value of SYT_USER_BOOK.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.ID
     *
     * @param id the value for SYT_USER_BOOK.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.USER_ID
     *
     * @return the value of SYT_USER_BOOK.USER_ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.USER_ID
     *
     * @param userId the value for SYT_USER_BOOK.USER_ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.BOOK_DATE
     *
     * @return the value of SYT_USER_BOOK.BOOK_DATE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Date getBookDate() {
        return bookDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.BOOK_DATE
     *
     * @param bookDate the value for SYT_USER_BOOK.BOOK_DATE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.BOOK_TYPE
     *
     * @return the value of SYT_USER_BOOK.BOOK_TYPE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Integer getBookType() {
        return bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.BOOK_TYPE
     *
     * @param bookType the value for SYT_USER_BOOK.BOOK_TYPE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setBookType(Integer bookType) {
        this.bookType = bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.FOOD_TYPE
     *
     * @return the value of SYT_USER_BOOK.FOOD_TYPE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Integer getFoodType() {
        return foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.FOOD_TYPE
     *
     * @param foodType the value for SYT_USER_BOOK.FOOD_TYPE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setFoodType(Integer foodType) {
        this.foodType = foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.CHECK_UID
     *
     * @return the value of SYT_USER_BOOK.CHECK_UID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Long getCheckUid() {
        return checkUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.CHECK_UID
     *
     * @param checkUid the value for SYT_USER_BOOK.CHECK_UID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setCheckUid(Long checkUid) {
        this.checkUid = checkUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.CHECK_TIME
     *
     * @return the value of SYT_USER_BOOK.CHECK_TIME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.CHECK_TIME
     *
     * @param checkTime the value for SYT_USER_BOOK.CHECK_TIME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.CREATE_TIME
     *
     * @return the value of SYT_USER_BOOK.CREATE_TIME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.CREATE_TIME
     *
     * @param createTime the value for SYT_USER_BOOK.CREATE_TIME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER_BOOK.STATUS
     *
     * @return the value of SYT_USER_BOOK.STATUS
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER_BOOK.STATUS
     *
     * @param status the value for SYT_USER_BOOK.STATUS
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}