package com.syt.hotel.model;

public class SytUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER.DEPT_ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Long deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER.NAME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER.PWD
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER.MOBILE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER.OPENID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER.IS_MANAGER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Boolean isManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYT_USER.STATUS
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER.ID
     *
     * @return the value of SYT_USER.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER.ID
     *
     * @param id the value for SYT_USER.ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER.DEPT_ID
     *
     * @return the value of SYT_USER.DEPT_ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER.DEPT_ID
     *
     * @param deptId the value for SYT_USER.DEPT_ID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER.NAME
     *
     * @return the value of SYT_USER.NAME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER.NAME
     *
     * @param name the value for SYT_USER.NAME
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER.PWD
     *
     * @return the value of SYT_USER.PWD
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER.PWD
     *
     * @param pwd the value for SYT_USER.PWD
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER.MOBILE
     *
     * @return the value of SYT_USER.MOBILE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER.MOBILE
     *
     * @param mobile the value for SYT_USER.MOBILE
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER.OPENID
     *
     * @return the value of SYT_USER.OPENID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER.OPENID
     *
     * @param openid the value for SYT_USER.OPENID
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER.IS_MANAGER
     *
     * @return the value of SYT_USER.IS_MANAGER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Boolean getIsManager() {
        return isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER.IS_MANAGER
     *
     * @param isManager the value for SYT_USER.IS_MANAGER
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setIsManager(Boolean isManager) {
        this.isManager = isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYT_USER.STATUS
     *
     * @return the value of SYT_USER.STATUS
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYT_USER.STATUS
     *
     * @param status the value for SYT_USER.STATUS
     *
     * @mbg.generated Tue Nov 24 08:48:21 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}